### ISSUE TITLE
Can't chain preprocessors in

### ISSUE THREAD

**Issue by whitneyit** [sergeyt/karma-typescript-preprocessor#15]
As you mentioned in [#10](https://github.com/sergeyt/karma-typescript-preprocessor/issues/10#issuecomment-65064451), the typescript preprocessor passes out a String to be consumed by `coverage`. It also gets passed in a String to be consumed by a preprocessor before it.

I'm currently using the [lodash](https://github.com/deltaidea/karma-lodash-template-preprocessor) preprocessor before the typescript preprocesssor, like so:

``` js
// karma.conf.js
preprocessors: {
    'src/js/**/*.js' : ['lodash', 'coverage'],
    'src/ts/**/*.ts' : ['lodash', 'typescript', 'coverage']
},
```

However, on [line 74 in `index.js`](https://github.com/sergeyt/karma-typescript-preprocessor/blob/8bf336071b822660b11eb12daa9d3e7a7fd592c7/index.js#L74) the source for the file is being read directly from the filesystem and the reference to [`content` on line 21](https://github.com/sergeyt/karma-typescript-preprocessor/blob/8bf336071b822660b11eb12daa9d3e7a7fd592c7/index.js#L21) is being ignored.

**Comment by goktugyil** [comment]
Does your coverage work?

https://github.com/sergeyt/karma-typescript-preprocessor/issues/70
