### ISSUE TITLE
Broken when compiling with module: "amd"?

### ISSUE THREAD

**Issue by davidparsson** [sergeyt/karma-typescript-preprocessor#22]
I'm trying to write both tests and code under test using TypeScript. I wanted to use this preprocessor to make the tests run, but I have been unable to get it to work when setting module to "amd", like this:

```
// ...
typescriptPreprocessor: {
  options: {
    module: 'amd',
    target: 'es5'
  }
}
// ...
```

The test is unable to find the code under test. Is this tested/supposed to work? Compiling with the `typescript` Grunt task, with the same TypeScript compiler arguments, and then running the JavaScript tests works just fine.

The options passed to the TypeScript compiler also contain `basePath` and `declaration`, which does not seem to be supported by the karma-typescript-preprocessor. Are those options the cause of this?

I have created a minimal example, running the same test for both of these cases: https://github.com/davidparsson/karma-typescript-amd

Am I doing something wrong?

**Comment by raghanag** [comment]
Hi @sergeyt could you please help me to fix the error, I am trying to use requirejs with karma + typescript where all the karma-mocha, karma-chai and required types and karma-requirejs is also used. And I have copied your test-main.js and it is working without errors if i dont include anything other than mocha and chai. But if include other libraries like the ones required by my test files to load, i am getting the below error. 

`
(function() {

    var specFiles = null;
    var baseUrl = '';
    var allTestFiles = [];
    var requirejsCallback = null;
    var TEST_REGEXP = /^\/src\/ts\/tests\/.*(spec|test)\.js$/i

    if (typeof window !== 'undefined' && window.__karma__ !== undefined) {
      baseUrl = '/base/src';
      var start = window.__karma__.start;
      requirejsCallback = function() {
        require(['mocha','chai','knockout','jquery','ojs'], start);
      };
  
      specFiles = [];
      for (var file in window.__karma__.files) {
        if ((/spec.js$/i).test(file)) {
          specFiles.push(file);
        }
      }
    }

  
    requirejs.config({
        baseUrl: baseUrl,
  
        paths: {
          'mocha': '../node_modules/mocha/mocha',
          'chai': '../node_modules/chai/chai',
          'knockout': '../node_modules/knockout/build/output/knockout-latest',
          'jquery': '../node_modules/jquery/dist/jquery.min',
          'ojs': '../node_modules/@oracle/oraclejet/dist/js/libs/oj/min/oj'
         
        },
  
        deps: allTestFiles,
  
        callback: window.__karma__.start
    });
  })();
`

and the error
![image](https://user-images.githubusercontent.com/11847063/65011756-8e5d0e00-d8c9-11e9-9881-2ab3d4c71614.png)


Please let me know what i am missing?

**Comment by sergeyt** [comment]
@raghanag having repo with repro would be helpful. it seems you have problem with requirejs configuration. please take a look at https://requirejs.org/docs/errors.html.

**Comment by raghanag** [comment]
Thanks @sergeyt actually, it is something to do with test-main and karma conf file, it was cleared now. Thanks a lot for your reply.
