### ISSUE TITLE
Unable to watch *.ts files without preprocessing/compiling them?

### ISSUE THREAD

**Issue by davidparsson** [sergeyt/karma-typescript-preprocessor#23]
Hi,

I'm trying to configure Karma to watch for changes on all `*.ts` files but only compile the files in `tests` directories (and their references), like this:

    module.exports = function(config){
      config.set({
        files: [
          "app/**/tests/**/*.ts",
          { pattern: "app/**/*.ts", watched: true, included: false, served: false }
        ],
        preprocessors: {
          '**/*.ts': ['typescript']
        },
        plugins: [
          //...
          'karma-typescript-preprocessor'
        ],
        typescriptPreprocessor: {
          options: {
            target: 'es5',
            sourceMap: false
          }
        }
      });
    };

However, when adding the second line under files, the typescript preprocessor gives me a huge amount of compiler errors. When the files are `included: false` and `server: false`, should they not be excluded from preprocessing as well? Is there any other way to achieve this?

Thanks for a useful preprocessor!

**Comment by sergeyt** [comment]
the preprocessor is just rewritten using https://github.com/sergeyt/typescript-simple, so now it should support latest compiler with all compiler options. Please retry again.
