### ISSUE TITLE
Running preprocessor without package.json

### ISSUE THREAD

**Issue by dvlscm** [sergeyt/karma-typescript-preprocessor#26]
I don't know if it's possible to do what I want to do. Here's hoping.

I've got a .NET MVC app. I uses TypeScript 1.4 at present, and I've just gotten karma to run jasmine tests on my build server (Jenkins). It works fine. But what I'd love to do is not include the .js/.js.map files in my Visual Studio project, and generate them on the fly on the build server when I run the karma tests. That seems tailor made for your preprocessor.

The problem is, when I do `karma start` to run the karma tests with the preprocessor in my `karma.conf.js` file, for each .ts file I get this complaint:

```
ERROR: [preprocessor .typescript]: Cannot find module 'typescript'
```

I've installed the preprocessor with `npm install karma-typescript-preprocessor --save-dev`. I even tried installing it globally. No luck. I get the same error.

My `karma.conf.js` file is in the Jenkins workspace directory for the job I'm running, and `karma start` runs fine when I'm not using the preprocessor and I include the .js/.js.map files.

My app isn't a node app, so I don't have a `package.json`. I tried putting one in the same directory as `karma.conf.js`just as an experiment, but that didn't help.

Any ideas on how to make the preprocessor work with my setup? This seems so close to working.

Here's my `karma.conf.js` file for reference:

```
module.exports = function (config) {
    config.set({
        basePath: '../..',
        frameworks: ['jasmine'],
        files: [
            'path/to/classes/models/*.js',
            { pattern: '**/*.js.map', included: false },
            { pattern: '**/*.ts', included: false }
        ],
        exclude: [
        ],
        preprocessors: {
            '**/*.ts': [ 'typescript' ]
        },
        typescriptPreprocessor: {
            options: {
                sourceMap: true, // (optional) Generates corresponding .map file. 
                target: 'ES5', // (optional) Specify ECMAScript target version: 'ES3' (default), or 'ES5' 
                noResolve: false // (optional) Skip resolution and preprocessing. 
            },
            transformPath: function(path) {
                return path.replace(/\.ts$/, '.js');
            }
        },
        reporters: ['dots', 'progress', 'junit'],
        junitReporter: {
            outputFile: 'js-test-results.xml'
        },
        port: 9876,
        colors: true,
        logLevel: config.LOG_INFO,
        autoWatch: false,
        browsers: ['PhantomJS'],
        captureTimeout: 20000,
        singleRun: true,
        reportSlowerThan: 1000,
        plugins: [
          'karma-jasmine',
          'karma-chrome-launcher',
          'karma-phantomjs-launcher',
          'karma-junit-reporter',
          'karma-typescript-preprocessor'
        ]
    });
};
```

**Comment by sergeyt** [comment]
@dvlscm try to `npm install typescript --save-dev`, it is required since karma-typescript-preprocessor does not depend on any typescript version, i.e. you should select the version.

**Comment by dvlscm** [comment]
Installing typescript globally does let `karma start` run. The problem now is that nothing seems to get preprocessed, meaning there are no *.js or *.js.map files generated for my *.ts files. That's a little puzzling. I wonder if it might have something to do with how my files are organized.

Here's the output I get from `karma start`:
```
C:\Program Files (x86)\Jenkins\jobs\projectx\workspace\Projects\vsproject1>karma start
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
WARN [watcher]: Pattern "C:/Program Files (x86)/Jenkins/jobs/projectx/workspace/Projects/project1/JavaScript/classes/models/*.js" does not match any file.
WARN [watcher]: Pattern "C:/Program Files (x86)/Jenkins/jobs/projectx/workspace/Projects/project1/app/js/classes/models/*.js" does not match any file.
INFO [PhantomJS 1.9.8 (Windows 8)]: Connected on socket 4uxHQm6U_iiziiYUZCeJ with id 17746127
PhantomJS 1.9.8 (Windows 8): Executed 0 of 0 SUCCESS (0 secs / 0 secs)
PhantomJS 1.9.8 (Windows 8): Executed 0 of 0 ERROR (0 secs / 0 secs)
```
I expected to see the two warnings about the *.js pattern not matching any files, because the preprocessor hasn't run yet to generate the *.js files (I assume). But there's no indication that karma is finding any files to preprocess, and it's clearly not running any tests in the end.

Here's how my files are organized on my Jenkins server:
```
Program Files (x86)
|--Jenkins
   |--jobs
      |--jobwithtests
         |--workspace
            |--Projects
               |--project1
                  |--karma.conf.js
                  |--JavaScript
                      |--classes
                          |--models
                              |--test.ts
               |--project2
                   |--app
                      |--js
                         |--classes
                             |--models
                                 |--classundertest.ts
```
My `karma.conf.js` has a `basePath` which should put me in the Jenkins workspace relative to the config file. The `files` in there are relative to that basePath. I assumed the `preprocessors` paths should be similarly relative. Maybe that's wrong? Here's what my config file looks like right now:
```
module.exports = function (config) {
    config.set({
        basePath: '../..',
        frameworks: ['jasmine'],
        files: [
            'Projects/project1/JavaScript/classes/models/*.js',
            'Projects/project2/app/js/classes/models/*.js'
        ],
        exclude: [
        ],
        preprocessors: {
            'Projects/project1/Scripts/typings/jasmine/jasmine.d.ts': ['typescript'],
	    'Projects/project2/Scripts/typings/jasmine/jasmine.d.ts': ['typescript'],
	    'Projects/project1/JavaScript/classes/models/*.ts': ['typescript'],
            'Projects/project2/app/js/classes/models/*.ts': ['typescript']
        },	
        typescriptPreprocessor: {
            options: {
                sourceMap: true,
                target: 'ES5',
                noResolve: false
            },
            transformPath: function(path) {
                return path.replace(/\.ts$/, '.js');
            }
        },
        reporters: ['dots', 'progress', 'junit'],
        junitReporter: {
            outputFile: 'js-test-results.xml'
        },
        port: 9876,
        colors: true,
        logLevel: config.LOG_INFO,
        autoWatch: false,
        browsers: ['PhantomJS'],
        captureTimeout: 20000,
        singleRun: true,
        reportSlowerThan: 1000,
        plugins: [
          'karma-jasmine',
          'karma-chrome-launcher',
          'karma-phantomjs-launcher',
          'karma-junit-reporter',
          'karma-typescript-preprocessor'
        ]
    });
};
```

Is there anything obviously wrong with how I'm organizing things that would keep the preprocessor from processing anything?

**Comment by sergeyt** [comment]
@dvlscm I did not see any obvious errors in your configuration, but as I noted before I did not checked your use case without package.json. Again try to add package.json into `Projects` working dir with locally installed typescript (i.e. `npm install typescript --save-dev`) and then try to run tests locally. After that you could add `npm install` step in your jenkins build script. I think that way things will work expectedly.
