### ISSUE TITLE
Generating .js files and leaving them behind

### ISSUE THREAD

**Issue by matthewjh** [sergeyt/karma-typescript-preprocessor#33]
Has anyone else had issues with karma-typescript-preprocessor generating .js files and leaving them behind? It's extremely annoying.

**Comment by sergeyt** [comment]
@matthewjh karma preprocessor works for single file/stream expecting that compiler generates only one file, but tsc generates .js files for all `<reference/>`s also. It seems using preprocessor is not effective for TypeScript projects. I suggest to prepare JS files for karma runner with gulp/grunt task. See also #30.

**Comment by matthewjh** [comment]
@sergeyt 

Isn't that true of most (all?) transpilers? I.e. they have to transpile dependencies of the file being transpiled. The traceur preprocessor seems to work pretty well.

**Comment by awk** [comment]
I'm suffering from this too - @sergeyt can you give more details on how you think a preparation step would help? I'm particular concerned that if the generated code is too different from the source .ts (file concatenation, different file paths) that it might be less convenient to debug the unit tests.

**Comment by fabiosussetto** [comment]
Same here. I'd use Gulp as a preparation step before running the tests, but how would you do that? I'd need to make karma watcher and gulp working together.

**Comment by jordanpotter** [comment]
This issue is causing frustration here as well. Any advice would be greatly appreciated!

Perhaps a `grunt`/`gulp`command to remove all `.js` files left behind by the preprocessor? Not sure how I feel about that :frowning:

**Comment by sergeyt** [comment]
the preprocessor is just rewritten using https://github.com/sergeyt/typescript-simple, so now it should support latest compiler with all compiler options. Please retry again.
