### ISSUE TITLE
Question: why copying original js files?

### ISSUE THREAD

**Issue by fabiosussetto** [sergeyt/karma-typescript-preprocessor#34]
Hi, I've noticed you copy the original js files (renaming them as *.ktp.ts) and then feed them as input to the typescript compiler. Why is that needed? Thanks.

**Comment by martiansnoop** [comment]
I am also interested in why this is.

**Comment by iamryandrake** [comment]
I'd like to know why all the *.ktp.ts files are generated and then displayed in my directory, without being cleaned up?

**Comment by daric81** [comment]
+1

**Comment by CrouseMatthew** [comment]
+1

**Comment by snajo** [comment]
+1

**Comment by snajo** [comment]
Can you give feedback please?

**Comment by DarthDerrr** [comment]
+1

**Comment by sergeyt** [comment]
the preprocessor is just rewritten using https://github.com/sergeyt/typescript-simple, so now it should support all compiler options. Please retry again.
