### ISSUE TITLE
error TS2307: Cannot find external module '...' ~ when using relative paths

### ISSUE THREAD

**Issue by cblair** [sergeyt/karma-typescript-preprocessor#36]
Probably related to this bug: https://github.com/Microsoft/TypeScript/issues/2192.

Their work-around for now is to run tsc from the root (/ on linux) directory. So a possible solution here is to have something like a runDir option in the options section of the config to specify the directory to run from.

**Comment by sergeyt** [comment]
the preprocessor is just rewritten using https://github.com/sergeyt/typescript-simple, so now it should support all compiler options. Please retry again.
