### ISSUE TITLE
Add Support for TypeScript 1.6

### ISSUE THREAD

**Issue by huma-hamid** [sergeyt/karma-typescript-preprocessor#41]
Add Support for TypeScript 1.6

**Comment by Ridermansb** [comment]
I use typescript 1.6.. so maybe my problem [report here](http://stackoverflow.com/questions/33367130/karma-mocha-with-typescript-results-cant-find-variable-require-or-empty-t) is because this?

**Comment by elCarda** [comment]
+1

**Comment by sergeyt** [comment]
the preprocessor is just rewritten using https://github.com/sergeyt/typescript-simple, so now it should support latest compiler with all compiler options. Please retry again.
