### ISSUE TITLE
Karma TypeScript PreProcessor  Cannot find module Angular and Name Space ng

### ISSUE THREAD

**Issue by sudhamsa** [sergeyt/karma-typescript-preprocessor#43]
Here is my **Karma Config**

    module.exports = function(config) {
      config.set({
        frameworks: ['jasmine', 'traceur'],

        files: [
          'app/**/**/httpMock/httpMock.interceptor.ts',
            'app/**/**/httpMock/httpMock.module.ts',
            'app/**/**/httpMock/httpMock.service.ts',
            'app/**/**/httpMock/httpMock.config.ts'
             ],
         exclude: [
            'modules/**/e2e_test/**',
            'app/**/e2e/**/*.js',
            'thirdparty/pioneer/featureFlag/**/*{t,T}est.js'
        ],

        preprocessors: {
            //'app/**/*.js': ['traceur'],
            '**/*.ts': ['typescript']
        },
        typescriptPreprocessor: {
            options: {
                sourceMap: false,
                target: 'ES5',
                module: 'commonjs',
                noImplicitAny: true,
                noResolve: true,
                removeComments: true,
                concatinateOutput: false
            },
            typings: [ 'typings/tsd.d.ts' ],
            transformPath: function (path) {
                return path.replace(/\.ts$/, '.js');
            }
        },
        browsers: ['Chrome'],
        reporters: ['spec', 'junit'],
        specReporter: { maxLogLines: 5 },
        junitReporter: {
            outputFile: './build/work/jasmine/TEST-results.xml',
            suite: 'COMP'
        },
        port: 9876
    });
    };

And I have the dev dependencies delcaed in package.Json and the preprocessor plugin installed. 

Here is the package.Json

    "angular": "^1.3.5",
    "definitely-typed-angular": "^1.0.1",
    "karma": "^0.13.7",
    "karma-chrome-launcher": "^0.1.4",
    "karma-cli": "^0.0.4",
    "karma-dart": "^0.2.8",
    "karma-jasmine": "^0.2.2",
    "karma-junit-reporter": "^0.2.2",
    "karma-spec-reporter": "0.0.16",
    "karma-traceur-preprocessor": "^0.4.0",
    "karma-typescript-preprocessor": "0.0.20",

I am not sure what causing the issue when i run the test task runner says.

     13 10 2015 10:19:50.276:ERROR [preprocessor.typescript]: Cannot find module 'angular' and namespace 'ng'.

       at C:/*****.ts

for all the four files. Can anyone point out what is wrong?

**Comment by ijemmy** [comment]
I have this problem before. Not sure if it's the same root cause.

In my case, we forget to include reference to /typings/tsd.d.ts file 

/// <reference path="../../../../../typings/tsd.d.ts" /> 

We concatenate all .ts into one file with grunt-ts so the reference issue didn't show up outside of unit test.

**Comment by tonyeung** [comment]
I use mocha and the errors went away after:

1. I added the mocha.d.ts file
2. included at the beginning of the list of files that get processed by tsc

If you use jasmine include the jasmine.d.ts file instead

**Comment by sergeyt** [comment]
the preprocessor is just rewritten using https://github.com/sergeyt/typescript-simple, so now it should support all compiler options. Please retry again.
