### ISSUE TITLE
Changes in source files ignored in auto watch mode

### ISSUE THREAD

**Issue by damirarh** [sergeyt/karma-typescript-preprocessor#46]
When I'm running Karma in auto watch mode, changes in TypeScript source file trigger tests to be run again, but any changes in the file are ignored - the tests are run against the source code as it was before the change. Only when I make a change in the test code, the tests are actually run against the changed source file.

Steps to reproduce the issue:

- Create the source file `src/subtract.ts`:

```
function subtract(a: number, b: number) : number {
    return a - b;
}
```

- Create the test file `test/test-subtract.ts`:

```
///<reference path="../typings/tsd.d.ts"/>
///<reference path="../src/subtract.ts"/>

describe('subtract method', () => {
    it('subtracts 2 numbers', () => {
        expect(subtract(2, 5)).toBe(-3);
    });
});
```

- This is my `karma.conf.js`:

```
module.exports = function(config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine'],
    files: [
        './src/*.ts',
        './test/*.ts'
    ],
    exclude: [
    ],
    preprocessors: {
      '**/*.ts': ['typescript']
    },

    typescriptPreprocessor: {
      options: {
        sourceMap: true,
        noResolve: false
      },
      transformPath: function(path) {
        return path.replace(/\.ts$/, '.js');
      }
    },
    reporters: ['progress'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false,
    concurrency: Infinity
  });
};
```

When I now make a change in `src/subtract.ts` to break the test, the tests are rerun and still succeed. I need to change `test/test-subtract.ts` as well, for the test to actually register as broken.

Below are the files needed to reproduce the issue:
[KarmaTS.zip](https://github.com/sergeyt/karma-typescript-preprocessor/files/83675/KarmaTS.zip)

**Comment by talmog** [comment]
+1

**Comment by sergeyt** [comment]
the preprocessor is just rewritten using https://github.com/sergeyt/typescript-simple, so now it should support latest compiler with all compiler options. Please retry again.

**Comment by frederikschubert** [comment]
Why the dependency on typescript-simple? Is there anything that speaks against using ts.transpile(source, options)? I think it would be better to just depend on typescript so one can easily map the version of the pre processor to the used typescript version.

**Comment by sergeyt** [comment]
@frederikschubert looks like `ts.transpile` is enough for the preprocessor since it ignores type checking. Thanks for suggestion.

**Comment by sergeyt** [comment]
closing since out of date

**Comment by Waldbillig-Thomas** [comment]
hi, so i just wanted to know what the status is here.
i really like the plugin, but i cannot seem to get it to work in combination with watch mode.

in karma i set the 'autoWatch' to true 'singleRun' to false,
in the tsconfig i set the 'watch' flag to true,

but no change i make in the watched files seems to trigger any kind of recompilation.

am i missing something here?
