### ISSUE TITLE
Error TS2318: Cannot find global value 'Iterable'

### ISSUE THREAD

**Issue by raulramaya** [sergeyt/karma-typescript-preprocessor#50]
Trying to have typescript output as straight es6 but when I do so I get the error:

`Error TS2318: Cannot find global value 'Iterable'`
`Error TS2318: Cannot find global value 'Iterator'`

My flags are as follows:

` typescriptPreprocessor: {
     options: {
        target: 'es6',
       }
    },`

Any ideas where I might be going wrong?   This all works when using tsc directly (outside of Karma).

**Comment by sergeyt** [comment]
@raulramaya the preprocess is just rewritten using https://github.com/sergeyt/typescript-simple, so now it should support all compiler options. Please retry again.
