### ISSUE TITLE
support full TS compiler config

### ISSUE THREAD

**Issue by rolandjitsu** [sergeyt/karma-typescript-preprocessor#52]
Is there a reason why you are limiting the config options that are passed to the compiler? Also, is this fixed on a specific version of TS?

Because it would be good to support whatever version of the TS compiler the user wants and the options should just be passed to the TS compiler and should not be limited to a couple.

**Comment by sergeyt** [comment]
@rolandjitsu the preprocessor is just rewritten using https://github.com/sergeyt/typescript-simple, so now it should support all compiler options
