### ISSUE TITLE
Cannot get it to run compile error

### ISSUE THREAD

**Issue by Ixl123** [sergeyt/karma-typescript-preprocessor#53]
Do you have a simple example where this plugin works?

I am getting this error when I try to use the preprocessor. Even when the file is empty I get the same error. 

`ERROR [preprocessor.typescript]: Cannot read property 'text' of undefined
at webapp/test/unit/testFeedbackEvaluation.ts`

Here is my **karma.conf**

`module.exports = function(config) {
  config.set({

    // base path that will be used to resolve all patterns
    basePath: '',

    reporters: ['progress', 'html', 'coverage', 'junit'],

    // frameworks to use
    frameworks: ['jasmine'],

    preprocessors: {
      '../app/shared/**/*.js': 'coverage',
      '../app/components/**/*.js': 'coverage',
      '../test/**/*.ts': ['typescript']

    },
    typescriptPreprocessor: {
      // options passed to the typescript compiler
      options: {
        sourceMap: false, // (optional) Generates corresponding .map file.
        target: 'ES5', // (optional) Specify ECMAScript target version: 'ES3' (default), or 'ES5'
        module: 'amd', // (optional) Specify module code generation: 'commonjs' or 'amd'
        noImplicitAny: true, // (optional) Warn on expressions and declarations with an implied 'any' type.
        noResolve: false, // (optional) Skip resolution and preprocessing.
        removeComments: true, // (optional) Do not emit comments to output.
        concatenateOutput: false // (optional) Concatenate and emit output to single file. By default true if module option is omited, otherwise false.
      },
      // extra typing definitions to pass to the compiler (globs allowed)
      typings: [
        '../typings/tsd.d.ts'
      ],
      // transforming the filenames
      transformPath: function(path) {
        return path.replace(/\.ts$/, '.js');
      }
    },

    // list of files / patterns to load in the browser
    files: [
      '../app/components/**/*.ts',
      '../test/unit/*.ts',

    ],

    htmlReporter: {
      outputDir: 'testResults/karma_html', // where to put the reports
      templatePath: null, // set if you moved jasmine_template.html
      includeMarkdown: false, // whether you want a README.md file generated along with the HTML or not
      focusOnFailures: true, // reports show failures on start
      namedFiles: false, // name files instead of creating sub-directories
      pageTitle: null, // page title for reports; browser info by default
      urlFriendlyName: false, // simply replaces spaces with _ for files/dirs
      reportName: 'reports', // report summary filename; browser info by default
      //experimental
      preserveDescribeNesting: false, // folded suites stay folded
      foldAll: false, // reports start folded (only with preserveDescribeNesting)
    },

    junitReporter: {
      outputDir: '../testResults/karma',
      useBrowserName: false
    },

    coverageReporter: {
      type: 'html',
      dir: '../coverageResults/karma',
      subdir: function(browser) {
        return browser.toLowerCase().split(/[ /-]/)[0];
      }
    },

    // web server port
    port: 9876,

    // enable / disable colors in the output (reporters and logs)
    colors: true,

    // level of logging
    logLevel: config.LOG_INFO,

    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: true,

    // start these browsers
    browsers: ['Chrome'],
    plugins: [
      'karma-phantomjs-launcher',
      'karma-chrome-launcher',
      'karma-jasmine',
      'karma-junit-reporter',
      'karma-html-reporter',
      'karma-coverage',
      'karma-typescript-preprocessor'
    ],

    // Continuous Integration mode
    singleRun: true,
    browserNoActivityTimeout: 30000
  });
};`

**Comment by sergeyt** [comment]
@Ixl123 please try v0.1.1 which includes 7ee54cd printing stack trace and properly invoking done callback, hope this helps to debug your issue.

**Comment by Fiontan** [comment]
Hi. We are experiencing exactly this issue. Notably, however, the issue does not occur in our local dev machines (windows) but is happening on our Ubuntu build machine. We are running 0.1.2, however, have tested with 0.1.1 and the same issue exists. Any help would be much appreciated.

**Comment by tdhulster** [comment]
Same error here - ERROR [preprocessor.typescript]: Cannot read property 'text' of undefined...
Downgraded to version 0.0.21 and things work fine, must have something to do with the upgrade to typescript-simple : https://github.com/teppeis/typescript-simple/issues/37

**Comment by Fiontan** [comment]
@tdhulster thanks for the reply. @sergeyt Downgrading does seem to work, however, things run REALLY SLOW and our application isn't in any way large YET...

**Comment by tdhulster** [comment]
@Fiontan Ended up not using the karma-typescript-preprocessor and adding the tsc command to my npm script before running tests with karma
e.g. `"scripts": {
   "tsc -p ./test/tsconfig.json && karma start karma.config.js"
 },`

**Comment by Ixl123** [comment]
@Fiontan and @tdhulster we ended up using gulp instead of karma-typescript-preprocessor
