### ISSUE TITLE
Wrong template strings transpilation

### ISSUE THREAD

**Issue by osharper** [sergeyt/karma-typescript-preprocessor#54]
`` `${foo.bar}.blabla` `` expressions transpiles to `` foo.bar + }.blabla` `` somehow that completely breaks the tests.

If it happens to have the string surrounded by backticks without any variable inside, like `` `bla-bla-bla` ``, backticks still persist in js output, not replaced with normal quotes.

When the inserted var is in the middle or at the end of template string, it behaves like this:
ts: `` `Expected room: ${expectedRoomId}, Factual room: ${filteredRoom.roomId}` ``
js: `` `Expected room: ${ + expectedRoomId + }, Factual room: ${ + filteredRoom.roomId ``

Using "version": "0.1.0" of your package.

**Comment by osharper** [comment]
there are also issues with transpiling expressions like `foo = bar => doStuff(bar)` so consider checking that you use right version of ts transpiler

**Comment by sergeyt** [comment]
@osharper please provide the files to reproduce the issue, I've just checked `${foo.bar}.blabla` expression is working in test folder of this repository running on nodejs v5.10 with karma v0.13.22.

**Comment by osharper** [comment]
Thank you for a quick reply. Sadly, I cannot offer you files form the working project. But I'll review tests of your project and try to reproduce issue on some artificial example.
