### ISSUE TITLE
Is there a way to use an existing tsconfig.json?

### ISSUE THREAD

**Issue by grofit** [sergeyt/karma-typescript-preprocessor#59]
Currently the examples show that you are basically embedding your tsconfig settings into the karma config, but is there a way to get it to use the project level `tsconfig.json`? as I have a layout like:

```
<root>
|- tests
   |- specs
      |- ... // Tests all in here
      |- karma.conf.js
|- tsconfig.json
```

I know some other typescript tools just automatically find tsconfig files others need to be told, but is there a way to use the existing file or do I need to just make my own copy in the karma conf?

**Comment by sergeyt** [comment]
@grofit try to use `project` setting, example:

```js
// karma.conf.js
module.exports = function(config) {
  config.set({
    preprocessors: {
      '**/*.ts': ['typescript']
    },

    typescriptPreprocessor: {
      // options passed to the typescript compiler
      options: {
        // relative path to tsconfig
        project: '../../tsconfig.json'
      }
    }
  });
};
```
