### ISSUE TITLE
Debug Failure. False expression when loading ts files

### ISSUE THREAD

**Issue by Duskfall** [sergeyt/karma-typescript-preprocessor#61]
Hello i am trying to make this work with karma but i get an error when loading typings and .ts files
![image](https://cloud.githubusercontent.com/assets/2528125/18543303/cb2937fc-7b37-11e6-944d-2776cc15e096.png)

Also is there an example with coverage too? Thanks!

**Comment by mrfatgoat** [comment]
I just tried to upgrade from 0.0.21 to 0.2.1 and I am experiencing the same issue.  Happens on every .ts file.

**Comment by bastijns-jeroen** [comment]
@Duskfall @mrfatgoat 
Exclude the definition files from the preprocessor and it will work ;)

For example:
`preprocessors: { '**/!(*.d).ts': ['typescript'] }`
