### ISSUE TITLE
ReferenceError: Can't find variable: exports

### ISSUE THREAD

**Issue by dcastro** [sergeyt/karma-typescript-preprocessor#67]
I have a few angularjs tests written in js, and being run with Karma + Jasmine + PhantomJS, and I'm now trying to convert them to Typescript.

I installed `karma-typescript-preprocessor`, and modified my `karma.conf` to look like the following:

```
    files : bowerFiles.concat([
      'app/components/**/*.js',
      'app/components/**/*.ts'
    ]),

    preprocessors: {
      '**/*.ts': ['typescript']
    },

    typescriptPreprocessor: {
      // transforming the filenames
      transformPath: function(path) {
        return path.replace(/\.ts$/, '.js');
      }
    },
```

However, adding a simple file like the following to my project results in an error:

test.spec.ts
```
export const x = 2;
```

>λ karma start
08 06 2017 16:04:47.019:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
08 06 2017 16:04:47.022:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
08 06 2017 16:04:47.045:INFO [launcher]: Starting browser PhantomJS
08 06 2017 16:04:50.124:INFO [PhantomJS 2.1.1 (Windows 7 0.0.0)]: Connected on socket 2_5-yeCFATVX-t1_AAAA with id 10979895
PhantomJS 2.1.1 (Windows 7 0.0.0) ERROR
  ReferenceError: Can't find variable: exports
  at app/components/educationDocuments/test.spec.js:2

Maybe this is a really trivial error, but I'm still new to this whole tech stack so I'm not sure where to go from here.

Thanks in advance.

**Comment by dcastro** [comment]
On a related note, I also tried installing [`@types/jasmine`](https://www.npmjs.com/package/@types/jasmine), and adding `import jasmine from 'jasmine'` to a typescript file results in the same `ReferenceError` error, even though VSCode's intellisense says everything looks fine.

Using `<reference path="" />` works though.

**Comment by Ian5015** [comment]
@dcastro Did you ever find a solution for this? I'm running into it now.

**Comment by dcastro** [comment]
@Ian5015 Nope.. let me know if you do :/

**Comment by Maximaximum** [comment]
Having the same issue
