### ISSUE TITLE
Support addmin additional files to tsc compile

### ISSUE THREAD

**Issue by raDiesle** [sergeyt/karma-typescript-preprocessor#9]
Hi Sergey,

thanks for fixes so far.
Because I need to add additional files in a pattern matcher 
to the current *Test.ts file being processed, it would be great to support it by the preprocessor as well.

Reason: I want to add .d.ts files to the file clob, e.g. so that </// references are not needed on top of files.

I did manuel in index.js but it is far from optimum.

**Comment by sergeyt** [comment]
using 'typings' options could help to avoid duplicate code
